services:
  - type: web
    name: django-project
    env: python
    buildCommand: cd django_project && pip install -r requirements.txt
    startCommand: gunicorn django_project.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
