services:
  - type: web
    name: django-project
    env: python
    buildCommand: pip install -r django_project/requirements.txt && cd frontend && npm install && npm run build
    startCommand: cd django_project && gunicorn django_project.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
