services:
  - type: web
    name: django-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd django_project && gunicorn django_project.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
