# Generated by Django 5.2.4 on 2025-08-30 20:05

from django.db import migrations, models

from django.db import migrations

def set_default_topics(apps, schema_editor):
    ChatSession = apps.get_model("chatbot", "ChatSession")
    for session in ChatSession.objects.all():
        if not session.topic:  # only update blank/null topics
            session.topic = f"Session {session.id}"
            session.save(update_fields=["topic"])

class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(set_default_topics),
    ]
